service: serverless-plugin-browserify-aws-sdk-parts

plugins:
  - serverless-p

provider:
  name: aws
  runtime: nodejs4.3

custom:
  webpackIncludeModules: true # enable auto including modules

functions:
  first:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: first
